# Generated by Django 3.2.14 on 2023-03-29 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userName', models.CharField(default='', max_length=15)),
                ('userType', models.CharField(choices=[('M', 'Manager'), ('U', 'User')], default='U', max_length=1)),
                ('userPhone', models.CharField(default='', max_length=11, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(regex='^01([0|1|6|7|8|9]?)?([0-9]{3,4})?([0-9]{4})$')])),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
            },
        ),
    ]
